services:
  webapi:
    #container_name: webapi-container
    image: ${DOCKER_REGISTRY-}webapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-WebApi
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - sqlserver
    networks:
      - docker-network

  sqlserver:
    #container_name: sqlserver-container
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: always
    environment:
      SA_PASSWORD: "Password#2024"
      ACCEPT_EULA: "Y"
    volumes:
      - C:\Dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
    networks:
      - docker-network

  prometheus:
    #container_name: prometheus-container
    image: prom/prometheus
    restart: always
    user: root
    hostname: prometheus
    volumes:
      - C:\Dados\volumes\prometheus\config:/etc/prometheus
      - C:\Dados\volumes\prometheus\data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - docker-network

  grafana:
    #container_name: grafana-container
    image: grafana/grafana
    restart: always
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge