CREATE LOGIN [contato_user]
    WITH PASSWORD = N'gHvgkflgVBnqvWnx=Ji{xnhcmsFT7_&#$!~<egdgIrhrFqmu', SID = 0x8DC3EF72C2E1D14186E68D3CF8E2CE91, DEFAULT_DATABASE = [DB_CONTATO], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

