# worker-contato-delete-queue-consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-contato-delete-queue-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-contato-delete-queue-consumer
  template:
    metadata:
      labels:
        app: worker-contato-delete-queue-consumer
    spec:
      containers:
      - name: worker-contato-delete-queue-consumer
        image: mtoyoki/worker-contato-delete-queue-consumer
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: worker-contato-delete-queue-consumer
spec:
  ports:
  - port: 8080
  selector:
    app: worker-contato-delete-queue-consumer
